### ISSUE TITLE
Advanced Filters - My Assignments and On Watch selected; Project that did not satisfy filter displayed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#1173]
User selected My Tasks and On Watch Tasks on Filter View, 3 Facilities displayed for Project Summary.
Screenshot Example

![filter_view_my_tasks_on_watch_3_facilities](https://user-images.githubusercontent.com/11938477/102127000-e27ed700-3e19-11eb-9a80-28cbbbc4ac3f.png)

User selected one of the 3 Facilities found with the filter, and "No tasks found" displayed on the Tasks tab.
Screenshot Example

![filter_view_my_tasks_on_watch_3_facilities_select_Boise_facility_none_found](https://user-images.githubusercontent.com/11938477/102127092-0d692b00-3e1a-11eb-9b0c-84f0964d13ed.png)

**Comment by LAlexMHllc** [comment]
NOTE: My Tasks and now My Actions, which will be changed to My Assignments. On Watch Tasks is now included in On Watch.

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/103419180-e91e8580-4b5f-11eb-92bd-6743dc62b5e8.png)


![image](https://user-images.githubusercontent.com/74916983/103419191-f5a2de00-4b5f-11eb-86a8-271c4b81b522.png)

**Comment by LAlexMHllc** [comment]
Still not filtering correctly.
Screenshot Example

![on_watch_my_assignments_no_results_found](https://user-images.githubusercontent.com/11938477/103574239-9285b400-4e9d-11eb-8dab-98bb72f12622.png)

**Comment by LAlexMHllc** [comment]
The same 2 facilities out of the 4 facilities found still have No results found.

**Comment by LAlexMHllc** [comment]
These 2 facilities should not be on the Facility Manager sidebar to be selected with this filter. Both have No results found.
Screenshot Example

![my_assignments_on_watch_No_found_results](https://user-images.githubusercontent.com/11938477/104047587-e0f1c600-51af-11eb-9baf-456c65c7d295.png)

**Comment by LAlexMHllc** [comment]
This still does not function correctly.

**Comment by LAlexMHllc** [comment]
Still not fixed.
Screenshot Examples of 3 Projects that did not match Filters

![my_assignments_on_watch_Juneau](https://user-images.githubusercontent.com/11938477/106295267-36088100-621e-11eb-9bab-8da49582958c.png)

![my_assignments_on_watch_Boise](https://user-images.githubusercontent.com/11938477/106295294-3c96f880-621e-11eb-89b9-38f0972e7963.png)

![my_assignments_on_watch_Baltimore](https://user-images.githubusercontent.com/11938477/106295314-44ef3380-621e-11eb-9379-b87eff5dc59f.png)

**Comment by LAlexMHllc** [comment]
NOTE: Facility was changed to Project

**Comment by LAlexMHllc** [comment]
Closing, since there have been several updates to filters, and more to come. Will test after tags/flags updated.
