### ISSUE TITLE
add the ability to document lessons learned

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#1431]
As a user I would like to document lessons learned

Title: Text
Description: text
Date: date
Stage: Enumeration
Assign Users:
Successes: like updates its a + sign with text however 2 fields, one is the findings, the next is the recommendation
Failures: like updates its a + sign with text however 2 fields, one is the findings, the next is the recommendation
Best Practices:  like updates its a + sign with text however 2 fields, one is the findings, the next is the recommendation
Files:
Links:
Related Task Category
Related Task
Related Issue Type
Related Issue
Related Risk
Updates:

**Comment by bluenevus** [comment]
some perspective on what a lessons learned is https://www.youtube.com/watch?v=cemERTeeQ7M and its purpose

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/114621257-7b174d80-9c7a-11eb-947d-0f8d5988d128.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/115310011-1442da00-a13b-11eb-9966-afc8c60d9ef2.png)

**Comment by LAlexMHllc** [comment]
Reopen, since Lessons is being moved to Project level, as well as other updates #2573
