### ISSUE TITLE
Prod has On Watch with 100% Progress

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#1435]
Screenshot Example

![prod_has_on_watch_with_100_progress](https://user-images.githubusercontent.com/11938477/104342866-4c49d980-54c9-11eb-8e95-a62ac3c83702.png)

**Comment by bluenevus** [comment]
For clarification, if a task or issue is at 100%, its no longer on watch automatically

**Comment by LAlexMHllc** [comment]
Make sure the calculations are fixed for stats on Project Summary and Facility Summary.
Screenshot Example

![100_complete_should_not_be_included_stats_on_watch_data_set](https://user-images.githubusercontent.com/11938477/104373982-2f280180-54ef-11eb-956d-d70f005d0917.png)

**Comment by LAlexMHllc** [comment]
Closing, since new requirement for On Watch with 100% Progress
