### ISSUE TITLE
admin users were granted automatic access to projects as users when they shouldn't

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#1705]
admin users were granted automatic access to projects as users when they shouldn't

they weren't available in the drop list to search and they do not display as existing users though going to their name shows they have privileges

![image](https://user-images.githubusercontent.com/3675043/107396150-7f34bc80-6acb-11eb-8a37-13631034413a.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
