### ISSUE TITLE
Should the spell check feature include the replacement suggestion?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#1899]
The spell check feature previously available has changed with the new release does not include the replacement suggestion but only a red line indicating a misspelling. Please advise if this is an issue or just the way configuration.

**Comment by curtismayer** [comment]
I think that our update to deal with the default right-click menu appearing when we do not want it to appear on the Sheet page is the reason spell check replacement suggestions no longer show up as they are right-click actions.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed for Edit Task on Kanban.

Screenshot Example - User clicks Task card to edit (not right-click)

![kanban_click_card_to_edit_not_right_click](https://user-images.githubusercontent.com/11938477/109825110-7e450580-7c07-11eb-8b9b-c5c2727fbcf1.png)

Screenshot Example - Edit Task Displays. User right-clicked a textarea and the Spell check menu did not display. User clicked Close.

![kanban_edit_task_right_click_spell_check_menu_not_display](https://user-images.githubusercontent.com/11938477/109825415-ce23cc80-7c07-11eb-9d7f-8db826a3129d.png)

Screenshot Example - The Duplicate/Move menu was displayed next to the card that was clicked.

![kanban_edit_task_close_modal_duplicate_move_menu_open](https://user-images.githubusercontent.com/11938477/109825566-f1e71280-7c07-11eb-9ad5-63185e2dd2d6.png)

**Comment by LAlexMHllc** [comment]
NOTE: In the above example, click to edit was used ONLY to show that the duplicate/move menu did not display because of right-click select open.
On Sheet view, user can right-click select open, then spell check.

**Comment by christopherandrewcalderon** [comment]
@LAlexMHllc In addition to the spell-check not working in the Kanban modal, the context-menu is persisting, correct?

**Comment by LAlexMHllc** [comment]
Sometimes the context-menu displays; other times not.
Sometimes it displays and the user has to click around to get it to be hidden; other times just click another spot.

**Comment by LAlexMHllc** [comment]
Map view and Sheet view - Edit Note - right-click menu does not match others.
Screenshot Example of Map view

![map_right_click_edit_note_input_context-menu](https://user-images.githubusercontent.com/11938477/110680981-4873c400-81a7-11eb-9a57-604e570a00ea.png)

Screenshot Example of Sheet view

![sheet_right_click_edit_note_input_context-menu](https://user-images.githubusercontent.com/11938477/110681078-66412900-81a7-11eb-8284-114d85d90df1.png)

**Comment by LAlexMHllc** [comment]
Needs to be fixed on Kanban - Edit Task, Edit Issue, and Edit Risk forms

**Comment by christopherandrewcalderon** [comment]
@juan-rivera-2020 Is the code for the form(s) still contained within the card(s)? Per our discussion.

**Comment by LAlexMHllc** [comment]
Closing, includes replacement suggestions
