### ISSUE TITLE
Admin Panel - Risks - Display error when click on 'Risk Stage' column for sorting

### ISSUE THREAD

**Issue by b-solution** [MicroHealthLLC/mPATH#1999]
<img width="1433" alt="Screenshot 2021-03-12 at 2 35 55 PM" src="https://user-images.githubusercontent.com/5988861/110922206-3b8ad800-8341-11eb-822f-36be0be9fe22.png">

<img width="1435" alt="Screenshot 2021-03-12 at 2 36 35 PM" src="https://user-images.githubusercontent.com/5988861/110922813-fa46f800-8341-11eb-9a77-43a608cae2a4.png">

**Comment by LAlexMHllc** [comment]
Clicked Risks Stages column header, and an Error screen displayed.
Screenshot Example

![admin_risks_error_sort_risk_stage_column](https://user-images.githubusercontent.com/11938477/110990802-d2f02b00-8341-11eb-9360-64e4258c417a.png)
