### ISSUE TITLE
Client Panel - Sheets view - Issue save button must be disabled until all required (*) fields were filled

### ISSUE THREAD

**Issue by b-solution** [MicroHealthLLC/mPATH#2062]
<img width="1433" alt="Screenshot 2021-03-17 at 5 34 10 PM" src="https://user-images.githubusercontent.com/5988861/111468555-7fb61800-8747-11eb-8859-2bc50da73dd0.png">

**Comment by LAlexMHllc** [comment]
Closing, since validation message displays instead
