### ISSUE TITLE
Unused routes still active

### ISSUE THREAD

**Issue by christopherandrewcalderon** [MicroHealthLLC/mPATH#2181]
The routes for facility manager and watch view are still active.

![image](https://user-images.githubusercontent.com/77029475/112560923-650c2080-8d91-11eb-9646-9edd49fb5245.png)

![image](https://user-images.githubusercontent.com/77029475/112560960-781ef080-8d91-11eb-95cf-5d72ce7d0d7e.png)

**Comment by LAlexMHllc** [comment]
Still needs to be fixed. Both routes still exists.

Screenshot Example of Facility Manager

![facility_manager_no_content_but_route_active](https://user-images.githubusercontent.com/11938477/113303921-8ad48080-92cf-11eb-9f58-83d3d96f6079.png)

Screenshot Example of Watch View

![watch_view_no_content_but_route_active](https://user-images.githubusercontent.com/11938477/113303991-9aec6000-92cf-11eb-9915-5027f715ce5b.png)
