### ISSUE TITLE
Portfolio Manager

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2327]
As a user I would like Portfolio Manager where given permission to this tab, I can see sheets to tasks, issues, risks, lessons learned, and kpi etc etc when that comes in for every program and every project.  In the sheet we need addition metadata like program name, project group name and project name which aren't in the regular sheets.  Group by filter would be nice so that it visually separates the groupings like so 

![image](https://user-images.githubusercontent.com/3675043/117320594-63d31680-ae5a-11eb-91b6-9dcab45f38e5.png)

by default, it should group by program name. 

I should then be able to apply the filters to filter the data including program and projects given its all inclusive.  Given that the fields are the same the grid should be the same though the content will have mixed values as the enumerations differ from projects so those enumerations need to be taken into consideration to filter

I should be able to update the data there as we do in sheets

Based on the filter, as a user, I want to be able to pivot the table like so https://pivottable.js.org/examples/ and save that as a report that is shared with enterprise data users or private.  When we pivot the data, the top part of the screen is the pivot table, the bottom section is the actual data that makes up the data pivoted like so  
![image](https://user-images.githubusercontent.com/3675043/117321247-f7a4e280-ae5a-11eb-938d-cc1c5f6f16fe.png)

**Comment by bluenevus** [comment]
data is read only from the enterprise view.  data should be entered at project/program level.  at portfolio, its a roll up to view it

**Comment by bluenevus** [comment]
this should include the new assignments feature #2516

**Comment by bluenevus** [comment]
we will need a portfolio level gantt viewer

**Comment by juan-rivera-2020** [comment]
Version 1 of this requirement ("Portfolio Viewer") has been deployed to QA for testing.  We're closing this issue, but will create another issue with the additional requirements (mainly CRUD functionality) here that are not included in the current version.  With CRUD, we can then appropriately be name it the Portfolio Manager.

**Comment by LAlexMHllc** [comment]
Closing, since Portfolio view is included.
