### ISSUE TITLE
Map should have project pushpin instead of group circle with count 3; not able to click to view Project Summary.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2429]
Screenshot Example

![map_view_should_have_project_pushpin](https://user-images.githubusercontent.com/11938477/116457868-f14ab100-a831-11eb-8b25-dfec3606761a.png)

**Comment by LAlexMHllc** [comment]
Had to reload

**Comment by christopherandrewcalderon** [comment]
@LAlexMHllc Could you please provide steps to reproduce this issue? I have attempted to reproduce but I was not successful.

**Comment by christopherandrewcalderon** [comment]
Do any of the projects there not have an address?

**Comment by LAlexMHllc** [comment]
After further testing, this issue is related to Issue #2429.
Did not notice that group count on the map was incorrect when clicked.
Screenshot Example

![map_with_single_project_with_group_instead_of_pushpin](https://user-images.githubusercontent.com/11938477/116564080-a765d780-a8d2-11eb-9736-3ecdb3b9e984.png)

**Comment by LAlexMHllc** [comment]
If you click another view tab, then return to map, the project pushpin displays instead of the group icon

**Comment by LAlexMHllc** [comment]
Closing, since issue has not occurred after updates.
