### ISSUE TITLE
per project ability to enable or disable task, issue, risk, lessons learned

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2437]
As an admin I would like the ability to enable or disable specific modules like  task, issue, risk, lessons learned and in the future KPI
![image](https://user-images.githubusercontent.com/3675043/116573722-0c253000-a8db-11eb-835a-7dcbf6aeab67.png)

This will allow them to use a specific module on a project that pertains to their workflow

**Comment by bluenevus** [comment]
it is configured by default which modules are used at the program level applied to all project but can be configured at the project level to enable or disable also

**Comment by LAlexMHllc** [comment]
Closing, since done for Overview, Tasks, Issues, Risks, and Notes. 
NOTE: Lessons is In Progress; and KPI, etc. TBD
