### ISSUE TITLE
Include admin/lessons screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2468]
lessons table, filters, forms, batch actions

**Comment by LAlexMHllc** [comment]
Clicking the "Lessons" link on the menu bar does not display the Lessons screen.
Screenshot Example

![admin_lessons_menu_link_click_does_not_display_screen](https://user-images.githubusercontent.com/11938477/118669268-9cacad00-b7c3-11eb-8eae-d14b22e7118e.png)

**Comment by LAlexMHllc** [comment]
The Lessons screen does not display when input URL. Whoops screen displays.
Screenshot Example

![admin_lessons_url_whoops_screen](https://user-images.githubusercontent.com/11938477/118669855-18a6f500-b7c4-11eb-868a-12e2d887fbdd.png)

**Comment by microhealthamand** [comment]
#2549
