### ISSUE TITLE
lessons learned goes with tasks, issues, risks as a tab after risk not on its own page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2497]
![image](https://user-images.githubusercontent.com/3675043/117051491-9c50e400-ace4-11eb-937d-ba1ec92e6357.png)

should be here

![image](https://user-images.githubusercontent.com/3675043/117051529-a541b580-ace4-11eb-8d6c-c3bfd6fab217.png)

the lessons learned are for a project that roll up into a program that will then be visible enterprise wide in the portfolio data viewer which I have a ticket in for

**Comment by bluenevus** [comment]
its always related to the project which it originated 
![image](https://user-images.githubusercontent.com/3675043/117051690-d4f0bd80-ace4-11eb-8570-7fee11f1f424.png)

**Comment by bluenevus** [comment]
remove submitted by
![image](https://user-images.githubusercontent.com/3675043/117051864-02d60200-ace5-11eb-9e59-93b018f82e96.png)

it should be the standard raci

![image](https://user-images.githubusercontent.com/3675043/117051850-fea9e480-ace4-11eb-81f2-45e3c644010e.png)

**Comment by bluenevus** [comment]
Stage needs to look like the stage everywhere else

![image](https://user-images.githubusercontent.com/3675043/117051922-12ede180-ace5-11eb-9ddb-9d0ac25d581c.png)

should be like 
![image](https://user-images.githubusercontent.com/3675043/117051947-1c774980-ace5-11eb-8e22-63e20cc2b0b0.png)

**Comment by LAlexMHllc** [comment]
Closing, Lessons moved to Project level and include graphical Stage
