### ISSUE TITLE
as a user, sheets should be default outside of preferences being configured and should be the first tab

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2503]
as a user, sheets should be default outside of preferences being configured and should be the first tab

![image](https://user-images.githubusercontent.com/3675043/117165017-2192d200-ad93-11eb-9f53-8ed4b145608d.png)

in fact, the map should go after the GANTT tab

**Comment by LAlexMHllc** [comment]
Closing, since Sheet view has priority.
NOTE: Order of view menu links and route priority to be fixed under other issues.
