### ISSUE TITLE
rename the repo to mPATH which means the corresponding pulls in dev, qa, prod needs to be adjusted

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2504]
![image](https://user-images.githubusercontent.com/3675043/117165376-70406c00-ad93-11eb-819c-e7821f5ee3a8.png)

**Comment by juan-rivera-2020** [comment]
Repo renamed mPATH on 7 May 21.  The SSH key and HTTP url have also been (automatically) updated.  QA server has been updated.  BO and DoS servers are scheduled to be updated on the first available weekend (NLT 9 May 2021).
