### ISSUE TITLE
as a user I would like ALL dropdown lists as searchable boxes that filters on what is typed

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2512]
![image](https://user-images.githubusercontent.com/3675043/117231918-36508380-adee-11eb-8bbc-d8b9f78d2080.png)

The filter should be fuzzy vs exact match.  Its those sequential combination of letters typed that are found in the enumeration as enumerations can have more than one word

**Comment by LAlexMHllc** [comment]
Closing, since this is fixed on Client Panel.
