### ISSUE TITLE
please assume 2 lines for program titles so that cards can all be the same size

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2520]
![image](https://user-images.githubusercontent.com/3675043/117338640-cdf4b700-ae6c-11eb-8fe5-d8d65a7ca81c.png)

**Comment by juan-rivera-2020** [comment]
Done and will be included in next release. 
![image](https://user-images.githubusercontent.com/72885316/117497073-eedd0b00-af45-11eb-95d4-43371eee1437.png)
