### ISSUE TITLE
rename categories to process area throughout the application

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2551]
![image](https://user-images.githubusercontent.com/3675043/117678921-d7886280-b17d-11eb-920d-0111b935bccc.png)

should be called Process Area

**Comment by juan-rivera-2020** [comment]
Client Panel, Exports, and Portfolio Viewer _category_ labels done (ie, renamed).  Admin Panel also started, just need to rename one more (elusive) label in Admin Panel.  Will handle tomorrow.

**Comment by LAlexMHllc** [comment]
Admin Panel: "Category" to "Process Area"

admin/tasks, admin/issues, admin/risks, admin/lessons screens
Filters - Process Area selected/submitted - Search status - Current filters

Screenshot

![admin_action_filters_process_area_search_status_change_category_to_process_area](https://user-images.githubusercontent.com/11938477/130090233-54387ac4-c385-4618-8c59-a1688335a6ba.png)


admin/process areas
New button, forms, messages
Screenshot Example

![admin_process_area_change_category_to_process-area](https://user-images.githubusercontent.com/11938477/130090864-1f2305e1-8333-4088-a23d-699a08b59846.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
