### ISSUE TITLE
the mpath logo needs to be much higher quality

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2554]
looks sort of worn out

![image](https://user-images.githubusercontent.com/3675043/117679885-a9efe900-b17e-11eb-8eaf-aed533fec3d9.png)

Can you also match the font on "Welcome To" and color it green OR orange like the logo

**Comment by LAlexMHllc** [comment]
![mPATH_logo_quality_and_color](https://user-images.githubusercontent.com/11938477/118672866-8d7b2e80-b7c6-11eb-813b-61159da80fbc.png)
