### ISSUE TITLE
Admin User form - Project Privileges: User with Write or Destroy (Delete) privilege should also have Read

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2580]
Screenshot Example

![user_project_privileges_should_have_read_with_write_or_delete](https://user-images.githubusercontent.com/11938477/118011498-1b19d280-b31e-11eb-8693-48b29c19786f.png)

**Comment by microhealthamand** [comment]
#2939

**Comment by LAlexMHllc** [comment]
Closing, user with Write or Destroy receives Read on submit
