### ISSUE TITLE
Modify the admin privileges

### ISSUE THREAD

**Issue by microhealthamand** [MicroHealthLLC/mPATH#2588]
Modify Admin privileges

**Comment by microhealthamand** [comment]
Program
![image](https://user-images.githubusercontent.com/74916983/118884857-fcd74800-b8c4-11eb-9c73-8c39669743b0.png)

project
![image](https://user-images.githubusercontent.com/74916983/118884801-eb8e3b80-b8c4-11eb-8df1-873c0c66118d.png)

![image](https://user-images.githubusercontent.com/74916983/118884973-21cbbb00-b8c5-11eb-8839-d239d92efd36.png)

**Comment by LAlexMHllc** [comment]
Closing, since admin/user privileges were updated
