### ISSUE TITLE
Project Sidebar:  List All (Active) Projects Regardless of Actions Count

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#2684]
Recently, a field user reported an issue regarding "missing data" and "missing project(s)".  After investigating this issue it was discovered that [sometimes] projects with 0 saved actions are not listed in the project sidebar.  This is problematic as users who want to add a Task / Issue / Risk will have no ability to do so in the Client Panel.  Further, not having the project listed in the sidebar may give a user the false (and worrisome) impression that their data has disappeared.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
