### ISSUE TITLE
Action with Important checked should have Important icon (star) on listing and popup cards.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2685]

**Comment by juan-rivera-2020** [comment]
Done 👍  
![image](https://user-images.githubusercontent.com/72885316/119850536-a3ca6e00-bedb-11eb-8b38-187404ad6097.png)

**Comment by LAlexMHllc** [comment]
NOTE: Image above is missing Important checkbox

**Comment by LAlexMHllc** [comment]
NOTE: Important icon on forms was dealt with for Issue #2683. This is for icon display on listing card and popup card.
