### ISSUE TITLE
flags marked important shows as no flags at this time when there is a flag marked

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2729]
![image](https://user-images.githubusercontent.com/3675043/120724837-9e07f600-c4a2-11eb-939d-e96067b0e44b.png)

**Comment by juan-rivera-2020** [comment]
Today we removed the text "No flags at this time".  If the action has no flags and is on schedule, the green calendar icon will be displayed.  Screenshot: 
![image](https://user-images.githubusercontent.com/72885316/120854215-d9f69600-c54a-11eb-86b7-15d45735d0a6.png)
