### ISSUE TITLE
Map view - Action forms: Flags bar should display above Name

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2775]
Tasks, Issues, and Risk forms
Screenshot Example

![map_form_flags_bar_should_be_above_action_name](https://user-images.githubusercontent.com/11938477/121549880-3d197a00-c9dc-11eb-9ddd-8177e11f9972.png)

**Comment by juan-rivera-2020** [comment]
This task was completed, but based on Curtis' design requirements (ie, in Map view, flag labels are hidden).
