### ISSUE TITLE
project dashboard is misleading or confusing

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2786]
![image](https://user-images.githubusercontent.com/3675043/121611304-f05a9100-ca25-11eb-813c-0242d5845adb.png)

there are things overdue, there are tasks completed, there are things ongoing, there are issues completed and overdue

the problem is by default the active filter is on as it should but it shouldn't apply to the overview and even after clearing the active filter the total tasks says 23 which is confusing

![image](https://user-images.githubusercontent.com/3675043/121611492-5f37ea00-ca26-11eb-8786-1edb255c5e6f.png)

**Comment by bluenevus** [comment]
I'm not sure what the answer is but the overview dashboards are confusing and right now its really active filter with the complete numbers because when you have active...complete will always be blank.  I'm not sure what the answer is but the simplest is to not apply filters for the time being to the overview dashboard

**Comment by bluenevus** [comment]
I just realized the 23 is actually the number of projects.  Its on the far right when it really makes more sense to put it into the group to sum up the total here
![image](https://user-images.githubusercontent.com/3675043/121612043-9f4b9c80-ca27-11eb-8a1e-5c338cf223f4.png)


Its also project status not projects status

**Comment by bluenevus** [comment]
then if you put a count above, to be consistent you should put it on the count of project groups here 

![image](https://user-images.githubusercontent.com/3675043/121612104-be4a2e80-ca27-11eb-9f16-1d278030f709.png)

**Comment by LAlexMHllc** [comment]
Stats counts fixed.
Still need to move projects count from next to Program Name to Project Status box (resize); and include Project Group count.
Screenshot Example on Sheet

![program_summary_include_project_status_count_and_project_groups_count](https://user-images.githubusercontent.com/11938477/125819360-de9b94cd-d544-4a38-8794-0891656a759d.png)

NOTE: Also fix on Map view

**Comment by LAlexMHllc** [comment]
Closing, fixed
