### ISSUE TITLE
When we add lessons learned, the stats need to show on the dashboards and landing page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2800]
![image](https://user-images.githubusercontent.com/3675043/121733541-9e674900-cac1-11eb-8028-6853cdcff46b.png)

**Comment by LAlexMHllc** [comment]
After update, Lessons does not display on dashboard

**Comment by LAlexMHllc** [comment]
Closing, since Lessons displays on dashboard Program cards
