### ISSUE TITLE
Edit Lesson - There is a slight delay for input to fill in, unlike the other forms

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2802]
Screenshot Example

![edit_lesson_delay_approx_1_second_fill_in](https://user-images.githubusercontent.com/11938477/121739221-4df3e980-cac9-11eb-9e63-08dc8c58fe97.png)

**Comment by christopherandrewcalderon** [comment]
Delay is due to the lesson data being fetched from the server. Lessons is different than tasks, issues, and risks, which are all currently being loaded at the same time whenever the app initially loads.

I have added a loader to indicate the data is being fetched when navigating to a lesson form.
