### ISSUE TITLE
stages in lessons learned should be just like stages in other areas

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2807]
this 
![image](https://user-images.githubusercontent.com/3675043/121751480-37a35900-cadc-11eb-89bf-6ee19b162bd0.png)

should be this

![image](https://user-images.githubusercontent.com/3675043/121751502-438f1b00-cadc-11eb-9fb3-dec1b420bb3a.png)

placement of everything needs to be consistent so they know and recognize the feature given its location

**Comment by bluenevus** [comment]
category is placed in a differnt location in lessons than on task, issues and risk

we need the same placement for the same form elements on each form

**Comment by LAlexMHllc** [comment]
Clicking on a Lesson Stage should select the stage

Screenshot Example

![clicking_lesson_stage_should_select_a_stage](https://user-images.githubusercontent.com/11938477/121952054-bc36e700-cd29-11eb-9d0c-eda931fb09af.png)
