### ISSUE TITLE
as a user, I just want to flag the tasks, issues, risk, lessons I want to use for briefings

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2809]
![image](https://user-images.githubusercontent.com/3675043/121754191-f01fcb80-cae1-11eb-900f-4d7706a73676.png)

so its "briefing" or "reports"  

really its reportable items that will be reported or briefed.  Not sure what term works best.

**Comment by juan-rivera-2020** [comment]
Completed and deployed to QA.  However, we plan to update the "Briefings" icon to the presentation icon from font-awesome library.
