### ISSUE TITLE
consistency is key.  it all needs to be the same controls, same look, same placement, same location etc

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2810]
updates everywhere looks like this

![image](https://user-images.githubusercontent.com/3675043/121758826-139e4280-caf1-11eb-9dac-e944b36a7312.png)

however in lessons learned it looks like this

![image](https://user-images.githubusercontent.com/3675043/121758841-231d8b80-caf1-11eb-8220-8d220f47d7b8.png)

one look, one feel, consistency across everywhere is important and MUST.

**Comment by LAlexMHllc** [comment]
See related Issue #2803

**Comment by LAlexMHllc** [comment]
Closing, all have blue with grey style now
