### ISSUE TITLE
I can't find lessons learned enumeration for stages

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2812]
![image](https://user-images.githubusercontent.com/3675043/121759092-15b4d100-caf2-11eb-95ec-87aa93df3b70.png)

I'm admin on the system and can't find where I configure these enumerations

![image](https://user-images.githubusercontent.com/3675043/121759141-53195e80-caf2-11eb-9e92-b2e1b3bc83e5.png)

**Comment by LAlexMHllc** [comment]
Closing, Lesson Stages on Admin Panel
