### ISSUE TITLE
Admin Panel - Tasks, Issues, Risks, and Lessons forms - Fix Files & Links: Include Add Link function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2893]
![admin_lessons_forms_include_Add_Link](https://user-images.githubusercontent.com/11938477/122795337-3667ee00-d28b-11eb-9dca-8f19ea592522.png)

**Comment by LAlexMHllc** [comment]
Add Link is included on form, but does not save link on submit.
Screenshot Example on task form

![admin_edit_action_form_files_and_links_add_link_file_not_saved_on_submit](https://user-images.githubusercontent.com/11938477/127368193-a89c45fb-5c7e-4053-b04e-5440683f8e8a.png)

**Comment by vinkMHllc** [comment]
Add a link in the text field and then press enter, in order to add multiple links.

**Comment by LAlexMHllc** [comment]
Closing, since clicking Enter with Add Links input, then clicking Update saved link.
NOTE: This functions differently then Client Panel.
