### ISSUE TITLE
Sheet View - Truncate text for Updates and Descriptions

### ISSUE THREAD

**Issue by christopherandrewcalderon** [MicroHealthLLC/mPATH#2922]
1. Truncate Updates and Descriptions to only show a limited number of characters to prevent table rows from growing in height.
2. Add ability to show full Update or Description text on hover/toggle/button press.

**Comment by LAlexMHllc** [comment]
Hover is used to show more text for Description and Update, but full text is not always visible. Scrollbar displays on hover, but user is not able to hover/scroll at the same time. Sometimes user still has to edit action to view all text for description or update.

Screenshot Example before hover

![sheet_view_lessons_table_description_update_long_text_before_hover](https://user-images.githubusercontent.com/11938477/125495166-9771565d-6242-4903-81b4-ea1ca311a307.png)

Screenshot Example of hover Description

![sheet_view_lessons_table_description_update_long_text_hover_description](https://user-images.githubusercontent.com/11938477/125495263-f2373a4d-a7ca-4778-b2db-bf15b3a03918.png)

Screenshot Example of hover Update

![sheet_view_lessons_table_description_update_long_text_hover_update](https://user-images.githubusercontent.com/11938477/125495300-fbdbaed8-040a-4cbe-90a1-96ae51e1315f.png)

**Comment by LAlexMHllc** [comment]
Closing, hover used. To view all text, user can arrow down while hovering.
