### ISSUE TITLE
as an admin, I would like to bulk assign permissions to users

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#2935]
as an admin, I would like to bulk assign permissions to users

Right now, I have to go to each account to individually assign users or sets of users permissions.  as an admin, I would like to bulk assign permissions to users

**Comment by bluenevus** [comment]
in the interim, can you run a script to give everyone read, write, delete for lessons learned?  This will need to be applied for both back office and dos

**Comment by LAlexMHllc** [comment]
Closing, since program admin can bulk assign users to ADMIN role, Project role, and Contract role
