### ISSUE TITLE
Flag Assignments and Accuracy

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#2984]
**_References: #2785 , #2786_**

In an ongoing effort to improve dashboard metrics, accuracy, and user experience, flags have been categorized into two main groups, **States** and **Tags**.  

**States** capture action statuses and are unique to the action.  For example, if a Task is _**ongoing**_, it cannot also be **_on hold_**.  If an Issue is a **_draft_**, it cannot be **_in progress_** or **_overdue_**, etc.

**Tags** capture how the user wishes to view their data.  It is more of an attribute that chraracterizes how the action will be "expressed" as opposed to a State which represents the action's current status within a workflow.  Now, for a visual example.

The image below is a screenshot of the Program Rollup and Project Overview Task card currently in QA branch.  It includes all seven States that make the sum of all Tasks.  Visually, if a user filters **_overdue_** Tasks, the Task count should be the exact number displayed by the overdue icon.  To further elaborate, if only the **overdue** filter is set, there should be no other values displayed in any other icon (except for **_overdue_**).

With the overarching goal of improving the user experience, these definitions will aim to reduce confusion and aid the user in interpreting the overview and rolllup data.
![image](https://user-images.githubusercontent.com/72885316/124302425-32f82080-db2f-11eb-8c2d-f236063a6903.png)

**Comment by juan-rivera-2020** [comment]
UI and Front end functionality is 90% complete.  Backend logic is required to perfrom simple validation of saved statuses.

**Comment by juan-rivera-2020** [comment]
**More clarification on flag statuses (mainly for backend):** 
- Draft takes precedence over all states.  For example, if a user in current mPATH version has a Task currently saved as ONGOING and DRAFT, logic needs to be written where DRAFT renders all other states false
- Between ONGOING and ONHOLD, ON HOLD will take precedence.  For example, if a user in current mPATH version has a task that is saved ON HOLD and ONGOING, logic has to be written such that if action is ONHOLD, all other states have to be equal to false
- Most importanly, if no flags or states are selected by user, logic has to be written to automatically save action as either PLANNED or IN PROGRESS (based on start date and current date).

**Comment by LAlexMHllc** [comment]
Closing, since State and Flag selectors are included.
Opening separate issues for different functions that still need to be fixed.
