### ISSUE TITLE
Summaries - Lessons Learned box: For narrow measure, break lines for "LESSONS LEARNED DATA COMING SOON" to avoid character cutoffs.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#2995]
Screenshot Example of Sheet view: Program Summary and Project Summary - Overview tab.

![overview_lessons_learned_narrow_measure_break_to_2_lines](https://user-images.githubusercontent.com/11938477/124640637-b2516100-de5b-11eb-881a-c70e101ab20c.png)

Screenshot Example of Map view: Program Summary and Project Summary - Overview tab.

![map_lessons_learned_box_characters_cutoff](https://user-images.githubusercontent.com/11938477/124642875-59cf9300-de5e-11eb-9763-c19bb9b5e857.png)

**Comment by juan-rivera-2020** [comment]
After: 

**With Data**
![image](https://user-images.githubusercontent.com/72885316/126807249-ec33e9e6-1962-4fb7-b15a-4d76a3fa5237.png)

**No Data To Display:** 
![image](https://user-images.githubusercontent.com/72885316/126807550-f7a3b242-1bf7-4aca-beb3-502023a7e45a.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
