### ISSUE TITLE
Most current Last Update on Sheet View may show current date and time, not the update date and time

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mPATH#3004]
I have been able to see this occur, just not sure how to reproduce it ... 

![image](https://user-images.githubusercontent.com/67476905/124821372-9e316080-df3c-11eb-8178-1304a4d3b918.png)

**Comment by LAlexMHllc** [comment]
Still not fixed. 
When more than one update, the current update text will display on the table with the previous submitted date/time.
Screenshot Example

![when_more_than_one_update_latest_text_displays_table_with_previous_submitted_date-time](https://user-images.githubusercontent.com/11938477/125811212-a6d0eb07-a42c-40e4-9791-5421cda8f3fd.png)

The first update displays correctly.
Screenshot Example

![first_update_displays_table_with_correct_date-time](https://user-images.githubusercontent.com/11938477/125811872-6039d38f-fa20-430e-afd4-3ecc28e58471.png)

Add another update on the same day.
Screenshot Example

![when_more_than_one_update_latest_text_displays_table_with_previous_submitted_date-time_2](https://user-images.githubusercontent.com/11938477/125812972-ce0e2806-4540-4059-ad49-46a4609d7adb.png)

**Comment by LAlexMHllc** [comment]
Closing, since current date does not display. Date issue is still not fixed. See Issue #3096
