### ISSUE TITLE
admin/users forms - Privileges: When Read gets unchecked, should automatically uncheck Write and Delete.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3110]
Unchecking Read should automatically uncheck Write and Delete BEFORE submit.
Screenshot Example

![user_privileges_when_Read_unchecked_automatically_uncheck_Write_and_Delete](https://user-images.githubusercontent.com/11938477/126176600-a451d981-9c31-46a8-9514-e770ae6ae73f.png)

**Comment by LAlexMHllc** [comment]
Currently, if Read is unchecked with Write and/or Delete checked on submit, the privileges will be unchanged due to the way Issue #2939 was fixed.
NOTE: Issue #2939 was reopened, so that the changes should be seen before submit. Also, this should make it clear to the user, which privileges are checked/unchecked before submit.

**Comment by LAlexMHllc** [comment]
Closing, this is intended function.

**Comment by microhealthamand** [comment]
Reopening this issue, as discussed with Curtis, this is expected behavior.

**Comment by LAlexMHllc** [comment]
Closing, fixed
