### ISSUE TITLE
as a user I would like the filter to be consistent.  just flags

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3114]
it should look like this in tasks
![image](https://user-images.githubusercontent.com/3675043/126247698-e3a8ce50-0d39-42f8-89d6-ae22c04a170b.png)

instead of issues and risk with the hamburger menu

![image](https://user-images.githubusercontent.com/3675043/126247721-23f9470f-f36b-47ad-8a3d-ebd3013c6a26.png)

**Comment by LAlexMHllc** [comment]
Closing, since Flags was changed to States to Display with Focus; and the More Filters hamburger menu will be removed from Issues and Risks tabs.
