### ISSUE TITLE
as a user, the default flag should be active

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3117]
the problem is that 9 out of 10 time as a user I'm working on only active tasks.

by removing the default to active, you are creating clicks 9 out of the 10 times in use case.  

![image](https://user-images.githubusercontent.com/3675043/126347879-294aa840-a50b-4ddf-b5c6-5adf439fbd29.png)

**Comment by bluenevus** [comment]
this should be done with the above task #3114 
https://github.com/MicroHealthLLC/mPATH/issues/3114

**Comment by LAlexMHllc** [comment]
Closing, since "Active" is no longer a State for actions
