### ISSUE TITLE
portfolio data viewer needs full compliment filters where the data fields match

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3128]
![image](https://user-images.githubusercontent.com/3675043/126649511-168f90cb-4b0f-449c-9385-c332bf56b7ec.png)

Right now, its way to hard to sift through.  we need full compliment of filters where the data fields match

![image](https://user-images.githubusercontent.com/3675043/126649721-21589fa3-7369-4fdd-aa5a-8b6968acfa33.png)

this might be where the hamburger menu works
![image](https://user-images.githubusercontent.com/3675043/126649935-024bbe1f-d7f8-4094-8bf9-8dcb66510f00.png)

where you can only sort by program right now here
![image](https://user-images.githubusercontent.com/3675043/126650004-6b25eb29-3ca5-4e7a-9d43-b62b5674e9a5.png)

**Comment by LAlexMHllc** [comment]
Closing, since Portfolio Filter included on Portfolio screen

**Comment by LAlexMHllc** [comment]
Still missing hamburger menu filters

**Comment by LAlexMHllc** [comment]
Closing, Process Area filter and Portfolio filters now included.
Hamburger filter will not be included. See #3459
