### ISSUE TITLE
Ongoing Status:  Set to either Open or Closed

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3200]
**As instructed by Director of IT:** 

The recent requirement to remove progress values from **_ONGOING_** actions warrants the need to further identify ONGOING actions as either **_open_** or **_closed._**  

Currently, actions that are both **_ONGOING_** and **_COMPLETED_** diminish the accuracy of filtering counts.  This modification aims to continuously improve flag filtering accuracy by preventing **_ONGOING_** actions from being grouped with **_COMPLETED_** actions.  

As one would assume, an **_ONGOING_** action becomes "closed" when the user provides a "DATE CLOSED" date.  

From a developer standpoint, actions that are "open", require no further action.  An _**ONGOING**_ action that is "open" simply means that the action is being actively managed by the user and does not have a DATE CLOSED date.  In terms of db requirments, similar to other flag states, the **_closed_** distinction is a simple boolean value (default:false) that gets assgined to **true** when the **_ONGOING_** action gets a DATE CLOSED value.  

Lastly, to clarify, "open" status is  merely a user (or client-facing) term.  There will be no need for labels or "open" values.  The end result of this modification is the ability to identify an **ONGOING** action as either _ONGOING, open_ or _ONGOING, closed_.

**Comment by LAlexMHllc** [comment]
Screenshot Example of successful Ongoing Closed

![ongoing_task_closed_due_date](https://user-images.githubusercontent.com/11938477/129915302-685e5deb-9113-4b71-b9d7-857c6b11571a.png)

The Status count for Ongoing has Total Ongoing (Closed Ongoing) - DONE
Should be able to distinguish between Ongoing Open and Ongoing Closed on the table.
Screenshot Example

![tasks_table_with_ongoing_open_and_ongoing_closed](https://user-images.githubusercontent.com/11938477/129915137-de87e489-a23a-4b9b-a89e-6fe5aad9478c.png)

**Comment by LAlexMHllc** [comment]
Also fix on Kanban and Calendar cards

**Comment by LAlexMHllc** [comment]
Closing, fixed
