### ISSUE TITLE
Change flag icon tooltip to popver with brief description of flag criteria 

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3210]
**As instructed by Director of IT**

The updated flags UI was desgined to improve accuracy, UX, and reduce confusion.  With the additional introduction of **Planned** and **In Progress** states, the user would benefit from knowing the criteria or definition of each state.  

This modification calls for a popover (ie, a tooltip for larger text areas) over the icons in the Program Rollup and Project Overview pages.    

Currently, the tooltips on these flags redundantly contain the name that is already provided in the label.  The content of the new popover aims to be more helpful by giving the user a brief description to aid in assigning or tracking action status.    
![image](https://user-images.githubusercontent.com/72885316/128070531-fdd2df4b-2f48-4726-87c8-77b47c5a032a.png)

**Example Popover UI:** 
![image](https://user-images.githubusercontent.com/72885316/128072140-8e04d0b2-7913-4f15-b977-c8fb87071a65.png)

**Comment by LAlexMHllc** [comment]
LESSONS flags missing popovers

Screenshot Example

![LESSONS_missing_popover_descriptions_for_flags](https://user-images.githubusercontent.com/11938477/130633231-4cf4c576-cfcd-4eaa-9829-018a6e117ad9.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
