### ISSUE TITLE
there is no way to unassign a project to a program though there is an option to do so in the menu

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3218]
there should be a way to simply unassign it from an already assigned program

![image](https://user-images.githubusercontent.com/3675043/128100733-d1862c4f-5f85-4c85-992a-75009f6f3afe.png)

![image](https://user-images.githubusercontent.com/3675043/128100748-fca57bd3-bc0b-4e04-a487-61a9266710cc.png)

This problem exists for project groups, state, program where there is no way to unassign it

**Comment by LAlexMHllc** [comment]
Closing, since this Batch Action should be removed, See Issue #4363
