### ISSUE TITLE
the point of this was to put the minimum complexity.  if the user creates a password more complex than the minimum, it should be permitted

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3228]
the point of this was to put the minimum complexity not an exact match criteria.  the user should be allowed to make their password more complex than the MINIMUM requirements

If the user creates a more complex password it should be allowed.

right now, if numbers aren't checked then the user can't use it.  If they don't check capital, they can't use it.  If the don't check special characters they don't use it.  If they use a password length greater than the minimum length set, they cant set it

![image](https://user-images.githubusercontent.com/3675043/128270594-168acb35-eec5-43a0-baef-89b92c9dd77c.png)

**Comment by LAlexMHllc** [comment]
Closing, since password with length >= minimum length with at least one character each for uppercase, lowercase, number, and special character will pass validation
