### ISSUE TITLE
Kanban View: Replace Flag dropdown to graphical UI 

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3236]
UI will be similar to that of Sheet View, but a more consolidated structure as seen in Map view.  

**End result:**
![image](https://user-images.githubusercontent.com/72885316/128417060-a35e3a30-d2b8-497f-93af-c171d557145c.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
