### ISSUE TITLE
Portfolio Viewer:  Add Advanced Filter sidebar (as seen in Client Panel)

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3244]
This sidebar will require Portfolio Viewer Adapatations.  The UI has already been built and just requires the backend data (ie, APIs) to populate the filters.  
![image](https://user-images.githubusercontent.com/72885316/128556447-23fd5ab6-3277-4ccc-b09c-c62077cfdab7.png)

1.   Filter 1:  **Programs, Project Groups & Projects** :  This dropdown will include options in data tree format containing Program names, Project Groups within those Programs, and Projects within those Project Groups.
**Example Filter 1 data in dropdown:**
![image](https://user-images.githubusercontent.com/72885316/128547888-2825c4a9-c742-45a6-990f-822f63e2f015.png)

2. Project Names Filter: (Since Filter 1 will contain this data, this filter won't be necessary in Portfolio Filter
3. Filter 2: **Program % Progress Range**:  Similar to the current filter in Client Panel but at the Portfolio Level.  Thus, this filter will provide filtering for Program progress percentages.
4.  **Action Users**:  Self-explanatory (this will filter all action users across all Programs)
5. All other filters, including the Tasks/Issues/Risks tab, will be required and will include Portfolio Level data.

**Comment by LAlexMHllc** [comment]
Closing, since Portfolio Filter included on Portfolio screen
