### ISSUE TITLE
Portfolio Viewer:   Add Presentation Mode

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3288]
This is part of the overall requirements for the Portfolio Data Viewer.  The presentation mode is aimed at giving user the ability to project all their data into a visually appealing presentation format that will aid in data digestion, interpretation, and decision making.  

Below is the UI that was recently deployed onto QA.  At the moment, it has only been implemented in Tasks for testing and to provide developer(s) with additional feedback: 
![image](https://user-images.githubusercontent.com/72885316/129804191-24953b95-8df4-4e76-bec3-31338e5d27bc.png)

**Comment by bluenevus** [comment]
great first go at this

**Comment by LAlexMHllc** [comment]
Closing, since Presentation Mode included
