### ISSUE TITLE
Presentation Mode - What should display on TASK PROGRESS for Ongoing Open and Ongoing Closed?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3293]
Screenshot Example

![presentation_mode_ongoing_open_and_ongoing_closed_TASK_PROGRESS](https://user-images.githubusercontent.com/11938477/129945451-1fb8e340-3165-4a2d-a28d-0224a314d16a.png)

**Comment by juan-rivera-2020** [comment]
Ongoing actions will not include progress status.  Will include in next QA deployment.

**Comment by LAlexMHllc** [comment]
Closing, fixed
