### ISSUE TITLE
admin Exports in csv and json should include all fields with enumerations and only the text field that is the name of the task issue risk or lessons learned

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#3299]
![image](https://user-images.githubusercontent.com/3675043/130061001-a9e1a76c-2de3-4d9f-a7f5-250e73761ed4.png)

Right now, the export is largely useless.  As an analyst, I expected to see all fields with enumerations to perform analytics on the data however, its largely missing the enumerations which are used to group and pivot the data.  The free text fields are not needed for analysis however, the name of the task, issue, risk, lessons learned is needed.

**Comment by bluenevus** [comment]
some fields you use simply for the ui like Kanban order or autocalculate which provide no value for reporting so those are not needed in the export as there is really nothing for an analyst to do with that data and should be removed from the exports

**Comment by LAlexMHllc** [comment]
Screenshot Example of Tasks CSV

![admin_tasks_csv](https://user-images.githubusercontent.com/11938477/131734571-7e50d7c5-7b76-4eae-a2de-2f5f54eaf7e6.png)


Screenshot Example of Issues CSV

![admin_issues_csv](https://user-images.githubusercontent.com/11938477/131734580-11ed173d-90af-48b5-b6db-46f3b53057d4.png)


Screenshot Example of Risks CSV

![admin_risks_csv](https://user-images.githubusercontent.com/11938477/131734785-71267ded-2c55-4753-8987-c9b300e32cf6.png)
