### ISSUE TITLE
Portfolio Viewer:  Add dark loading screen in all other tabs

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3326]
Although a dark loading screen has already been implemented in the Portfolio Viewer landing screen (ie, Tasks tab), all other tabs are loaded on click.  This creates a small delay in fetching data (for Issues, Risks, and Lessons).  A dark loading screen in all other tabs will improve UI and UX by reassuring the user that their data is loading.  Additionally, this will prevent user from viewing the seemingly awkward empty data UI.

**Comment by LAlexMHllc** [comment]
Closing, fixed
