### ISSUE TITLE
Program Viewer: Fix Issues filtering from Program Rollup page

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3511]
From this view (Sheet/Program Rollup), clicking any flag icon should direct user to Program Viewer (works as expected).
![image](https://user-images.githubusercontent.com/72885316/135475703-8add0c17-5f5e-4dbe-92cd-93cc93329741.png)

Once user is in Program Viewer, the expectation is to have only data of that single flag (works as expected in Tasks, Risks, and Lessons, as seen below):
![image](https://user-images.githubusercontent.com/72885316/135476130-71abcf5d-36df-403f-8df4-a7d6e25c9ff2.png)

The Issues tab has the correct flag selected, however, it displays no data:
![image](https://user-images.githubusercontent.com/72885316/135476408-0605c38f-7fe7-42b2-a992-084dada88458.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
