### ISSUE TITLE
Lessons stats should update on Program Summary dependent upon filters

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3536]
Screenshot Example

![program_summary_lessons_stats_should_update](https://user-images.githubusercontent.com/11938477/135866807-b15d40b9-c93f-435b-a175-edd760083e63.png)

**Comment by LAlexMHllc** [comment]
Not fixed after last update

**Comment by vinkMHllc** [comment]
Fixing in https://github.com/MicroHealthLLC/mPATH/pull/3424

**Comment by LAlexMHllc** [comment]
Closing, fixed
