### ISSUE TITLE
Calendar view: Remove extra text from card with In Progress flag

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3639]
Screenshot Example

![calendar_with_InProgress_flag_remove_extra_text](https://user-images.githubusercontent.com/11938477/142489446-40a96f9c-1528-4955-a2a0-0c5ac55c1f48.png)

**Comment by vinkMHllc** [comment]
Fixed
![Screenshot 2021-11-22 at 11 24 41 AM](https://user-images.githubusercontent.com/86612095/142897917-c2a9a92e-6ef2-422b-860c-dbe163273894.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
