### ISSUE TITLE
Client Panel - Open Contract Lesson should display Edit form, not New form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3724]
Screenshot Example

![click_client_panel_contract_lesson_to_open](https://user-images.githubusercontent.com/11938477/146572754-77fc2ed4-5150-41f6-ab74-4a4fd05d40fe.png)

![click_client_panel_contract_lesson_to_open_should_display_Edit_not_New_form](https://user-images.githubusercontent.com/11938477/146572770-a3cd093d-e418-4887-945f-d2f8b8473ee7.png)

**Comment by LAlexMHllc** [comment]
NOTE: Form should display just below line, so the tabs are not visible, like Project Lesson form

**Comment by LAlexMHllc** [comment]
NOTE: The lesson displayed after page reloaded.

**Comment by microhealthamand** [comment]
I can't reproduce issue.

**Comment by LAlexMHllc** [comment]
Closing, Edit Lesson displays filled in after last update
