### ISSUE TITLE
Contracts should also be included in Program Data Viewer

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3761]
Like Projects, clicking on any of these status icons should take user to Program Data Viewer.  The feature currently exists for Projects, so newly added Contracts stats will require same functionality.  
![image](https://user-images.githubusercontent.com/72885316/148082435-ca18dea8-04bf-42db-9fb6-705eafd8e14e.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
