### ISSUE TITLE
Left sidebar menu: Should display full Group Name on hover

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3783]
Screenshot Example

![group_name_left_sidebar_display_full_name_on_hover](https://user-images.githubusercontent.com/11938477/148406452-4dcc6dc4-3206-4fbe-b23b-a7155875ed8c.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![group_name_left_sidebar_display_full_name_on_hover_2](https://user-images.githubusercontent.com/11938477/148426008-17028086-b1ae-425a-8045-439fa3f7b3dd.png)

**Comment by LAlexMHllc** [comment]
NOTE: On hover function is not necessary for narrow measure, since complete Names display.
Screenshot Example

![sidebar_menu_narrow_measure](https://user-images.githubusercontent.com/11938477/148427043-21f31946-4241-4a01-9462-c57cf3c4e4e2.png)

**Comment by juan-rivera-2020** [comment]
Modified to show full Group name

**Comment by LAlexMHllc** [comment]
Closing, fixed
