### ISSUE TITLE
*Program Data Viewer:  Fix contract form update functionality 

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3787]
_*mpath-dev only.  Will deploy to mpath-qa upon completion of these requirements._

  **Project/Contract toggle** was recently added to Client Panel Program Summary.  In Program Data Viewer, contract form data can now be viewed when clicking row.  However, form editing is not yet functional. 

![image](https://user-images.githubusercontent.com/72885316/148470916-72975027-0cd7-4048-ab49-6b8c14bef91c.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
