### ISSUE TITLE
Project Contract form: Currently, only required field is "Current PoP End"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3803]
Screenshot Example

![project_contract_form_only_current_PoP_required](https://user-images.githubusercontent.com/11938477/148823613-4cfc38c2-4aad-440f-8d89-88a19959a706.png)

**Comment by juan-rivera-2020** [comment]
Removed * from Current PoP End filed.  Added required "*" to Contract Name and Contract Nickname fields.
 
![image](https://user-images.githubusercontent.com/72885316/152575472-f52d438e-804a-42ae-aa9b-89af90679f5d.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
