### ISSUE TITLE
Sheet view: Program Summary should include "PROJECTS/CONTRACTS" toggle

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3816]
Screenshot Example

![sheet_view_should_include_PROJECTS-CONTRACTS_toggle](https://user-images.githubusercontent.com/11938477/149170135-82120ef6-c67c-481f-8065-a6d8aa4454f7.png)

**Comment by juan-rivera-2020** [comment]
Left out intentionally until other components were finished.  My latest update completed all dependencies for toggle therefore, it has been added.

**Comment by LAlexMHllc** [comment]
Closing, fixed
