### ISSUE TITLE
Program Settings and Client Panel Groups (bug/missing data)

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3848]
Groups page in Program Settings was recently modified.  In a recent update, the API for groups was changed.  This change of source data results in missing contracts from Groups count in Project Sidebar as well as Groups Table.  This is a significant bug that needs to be fixed ASAP.  Fix will be completed on next work day (Jan 18th, 2021).

**Comment by LAlexMHllc** [comment]
Closing, fixed
