### ISSUE TITLE
Team View - Search appears to only search the data displayed

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mPATH#3865]
This came in from the DOS project team.

The Team View search functionality appears to only search the data being displayed when it should be searching across ALL of the data that would be included in the Team View.

For example, DOS has about 200 team members.  

The user can use the Displaying field (lower right) to identify how many records to show:  ![image](https://user-images.githubusercontent.com/67476905/151180129-e6ad8ccf-ca4f-4458-b679-c648244c389a.png)

If the Displaying field is set to a lower number such as 15, and if the person the user is trying to find is not within the 15 records being displayed the system will not find them while performing a search.  Again, this is because it appears that search is only searching the 15 records being displayed when it should be searching across all 200 records.

**Comment by LAlexMHllc** [comment]
Still does not function

**Comment by LAlexMHllc** [comment]
Tests today failed as well.

Screenshot Example of Search when Displaying 100 Per Page - CORRECT

![team_screen_only_searches_visible_1](https://user-images.githubusercontent.com/11938477/152178716-16aa7eb9-b315-4d74-9b69-7fdb05945d66.png)

Screenshot Example of Search when pagination is less than count - INCORRECT

![team_screen_only_searches_visible_2](https://user-images.githubusercontent.com/11938477/152178871-12d4a44e-c105-47fe-b7eb-9f41905c8ebc.png)

![team_screen_only_searches_visible_3](https://user-images.githubusercontent.com/11938477/152178964-252acc53-df55-4a82-b3d4-5007c76924b6.png)

Screenshot Example of incorrect display for Search, incorrect display X per page, missing entries.

![team_screen_only_searches_visible_4](https://user-images.githubusercontent.com/11938477/152179041-30e21da3-0622-4d8b-ac0c-4bf74750defe.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
