### ISSUE TITLE
User with Contract Write privilege should be able to Add/Edit action

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#3914]
Task, Issue, and Risk forms.
Sometimes an Alert displays after Save clicked. Action does not get saved.
Screenshot Example

![contract_task_save_clicked_user_with_Write_priv_denied_alert_displayed](https://user-images.githubusercontent.com/11938477/153014577-16e22794-f845-49ec-912f-f6e827dcb1d5.png)

**Comment by microhealthamand** [comment]
I can't reproduce this issue. Should be fixed in latest privileges changes. @LAlexMHllc

**Comment by LAlexMHllc** [comment]
Closing, fixed
