### ISSUE TITLE
Program Settings Group page (Client Panel), requirements

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3919]
Below are the features I want as an Admin user of the **Program Settings Groups** page:

- [x] Create a new Group native to the Program (created in Client Panel, avoiding the need to create in Admin Panel)
- [x] Option to import a Group name from Portfolio Level (ie, the Admin Panel)
- [x] Bulk import Portfolio Group Names
- [x] I want the ability to edit Program level Group names (Portfolio-level Group names will not be editable at the Program Level)
- [x]  I should be able to delete Groups that were created within the Program
- [x] I should be able to remove (but not delete) Group names that were imported from Portfolio Level
- [x]  I don't want my Program groups to be available at the Portfolio Level (ie, to users outside of my Program)
- [x] I want a Groups table that lists all Projects and Contracts within the Group

UI for this page:
![image](https://user-images.githubusercontent.com/72885316/153038119-8e4a933b-9f28-4c6f-b4aa-7ece6935f27c.png)

**Comment by LAlexMHllc** [comment]
Reopening, since all items not checked

**Comment by LAlexMHllc** [comment]
Closing, since all requirements checked
