### ISSUE TITLE
Program Summary:  Show/Hide Action Cards based on priveleges

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#3972]
We recently discovered that the Project / Contract toggle circled here breaks the program data  if recently implemented privleges are not handled properly.  This issue is being opened to implement UX-friendly features that will show/hide Task/Issues/Risks card data based on read-permissions. 
![image](https://user-images.githubusercontent.com/72885316/154709652-ed85eaeb-dcb0-46c7-8e1c-30648b8c965c.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
