### ISSUE TITLE
Additional Requirements for Groups

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#4025]
### (1) Seed a Group named, "Unassigned" for Projects and Contracts without a Group
As a user, I want to keep my Contracts and Projects data, even if I get rid of its original Group.  For example:  If I have a group named _Group ALPHA_ and it has 15 projects and 3 contracts, I may want to discard this group, eventhough I haven't yet determined a new group to reassign my contracts and projects to .

I would want to do this action in Program Settings Group page with the following expectations:

- By clicking on the delete icon, if the Group was originally created in my Program, it will delete the Group, but reassign its projects and contracts to an entity/group named _Unassigned_.  

- By clicking on the delete icon, if the Group was imported from the Portfolio (ie, Admin Panel), it will remove the Group from my program.  The projects and contracts created in my program will also be reassigned to an entity named _Unassigned_.  
- The Unassigned group will be a portfolio level group entity.  However, at the program level, the Unassigned group will only contain (a) unassigned data created within the program or (b) unassigned data imported by the program
- In the Admin Panel, as expected, the Unassigned Group will contain data that was created in the Admin Panel, but not assigned a Group nor Program.

### (2) Distinguish Portfolio level Groups from Program level Groups
As a Program Admin, when I'm looking at the Groups table in the Program Settings Goups page, I want to distinguish portfolio groups from program groups.

As a developer, I would create a value that is of boolean type and add it as an attribute to Groups.  For example, in each group object, I would add a key named "isPortfolio".  By default, I would set its value to **true**.  If a Group is created at the program level, it would set its value to **false**.  This is just an example and more brainstorming is recommended as more entities in the near future will require a similar value to determine its program/portfolio level.

If isPortfolio is false, that is, if the Group was created at the Program Level, it should not be listed in the Admin Panel Groups table.  

### (3) Admin Panel Housekeeping
Lastly, in Admin Panel, Project Groups need to be removed from under the Projects tab and:
1.  Groups (not Project Groups) will be its own tab
2.  When creating new Projects, Group should not be required and should default to Unassigned (if Group isn't selected)

### (4) Program Settings Groups page Workflow
As seen in screenshot below, the **Program Settings Groups** page will display a table containing the two types or levels of  mpath groups.  That is, Program Groups and Portfolio Groups.

The most updated UI distinguishes the two types of groups by a blue circle.  The blue circle denotes Program Groups.  The groups without the blue circle are Portfolio Groups.  Other Program Group identifiers include a trash can icon button.  This 
represents a functional difference when compared to the Portfolio Group icon, which is a circle-minus sign.

The trash can icon button represents the ability to delete.  The circle-minus icon represents the ability to remove.  Essentially, users can delete groups that were created within the program.  Portfolio Groups can only be removed from the program, not deleted.  Once a program administrator removes a Portfolio Group from their program, it will no longer be included in the Groups table.  However, Portfolio Groups that are removed or not listed in the Groups table can be easilyy imported by clicking the _Add Portfolio Group(s)_ button (this functionality has already been implemented).  

For both types of groups, deleting or removing a group will initiate the transfer of all data (ie, contracts and projects within the group) to the Unassigned group.  
![image](https://user-images.githubusercontent.com/72885316/157681226-76cb9905-dae7-4830-b6f9-46da88ebfa41.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
