### ISSUE TITLE
User with Program Privilege - Read privilege on a Contract tab: Should be able to view Contract without Read privilege under Contract Privilege

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4034]
Screenshot Example

![user_with_Program_Priv_Read_Contract_tab_without_read_Contract_Priv](https://user-images.githubusercontent.com/11938477/156650613-7b4a486a-3107-42d3-9b5c-ea1bf2a78618.png)

**Comment by LAlexMHllc** [comment]
NOTE: Privileges function correctly for user on Dev Testing program, but not the other programs.

**Comment by microhealthamand** [comment]
I can't reproduce this issue @LAlexMHllc

**Comment by LAlexMHllc** [comment]
Closing, fixed
