### ISSUE TITLE
Project dashboard screen: Include ability to view overall task list in one screen that shows who is responsible for each.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#404]

**Comment by bluenevus** [comment]
need mockup

**Comment by LAlexMHllc** [comment]
Screenshot Example of Overall Tasks List

![overall_tasks_list_with_assigned](https://user-images.githubusercontent.com/11938477/97352933-b9a28280-1869-11eb-88ac-dc8cb4168ac7.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of Overall Tasks List with Assigned

![overall_tasks_list_with_assigned](https://user-images.githubusercontent.com/11938477/97354511-de97f500-186b-11eb-923c-5f244b537992.png)

**Comment by LAlexMHllc** [comment]
Closing, since Portfolio Data Viewer has tasks, issues, risks, and lessons for all programs/projects
