### ISSUE TITLE
Admin Panel: update filters on tasks, issues, and risks to be able to exclude items in Inactive Programs and Projects

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mPATH#4094]
In the Admin Panel, update the filters on the tasks, issues, and risks pages to add the ability to exclude items in Inactive Programs and Projects.  The filter should be a checkbox that is checked by default and is labeled "Exclude Inactive Items". This checkbox and label can be added just above the Filter button as it will rarely be changed. When this is checked it means that any tasks, issues, and risks should be filtered out of the results if the Project and/or Program in which they exist is marked with a **State** of **_Inactive_**.  If it is not checked, then there is no filter.

**Comment by LAlexMHllc** [comment]
Closing, fixed
