### ISSUE TITLE
Program Settings Users: Add User(s) to Program should have users as options, when user(s) not included exists

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4099]
Sometimes the form displays with "No Portfolio Users Found" message, when it should have found users.
Screenshot Example

![add_users_to_program](https://user-images.githubusercontent.com/11938477/158656907-618d4d1c-f452-43ee-8b2f-e33570809c17.png)

**Comment by LAlexMHllc** [comment]
Sometimes the drop-down select displays without options, when users should display.
Screenshot Example

![add_users_to_program_drop-down_without_options](https://user-images.githubusercontent.com/11938477/159014623-eea12ace-c50a-4b48-9f33-af19cd92ce15.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed

**Comment by LAlexMHllc** [comment]
Reopening, since issue returned.
Screenshot Example

![program_settings_users_Add-User_to_Program_options_should_consistently_display](https://user-images.githubusercontent.com/11938477/165596063-3a8da0a7-0b05-4862-ba15-2a5aa1b14c62.png)

**Comment by juan-rivera-2020** [comment]
Reproduced display issue locally.  Working on fix.

**Comment by LAlexMHllc** [comment]
Closing, seems fixed
