### ISSUE TITLE
Add User(s) to Program should include all active users in Portfolio not assigned to that specific Program

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4294]
Add User(s) to Program should also include user(s) not assigned any Program.
Screenshot Example

![add_users_to_program_drop-down_without_options_should_include_user_not_assiged_any_program](https://user-images.githubusercontent.com/11938477/165960707-15d6ec5b-fbc1-44c7-92d6-8e6dbabfa2e8.png)

**Comment by juan-rivera-2020** [comment]
@microhealthamand in this api, please add all users within the instance (currently, this api only fetches users assigned to a program). 
![image](https://user-images.githubusercontent.com/72885316/165969446-2a60f4a7-cd6f-4829-8948-ce5a6a3e211d.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed

**Comment by LAlexMHllc** [comment]
Closing, fixed
