### ISSUE TITLE
Admin Panel:  Groups table should not contain any data created within program

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#4331]
**Issue:**  Admin Panel Groups table should not display Groups created in a program
**Task:**  Remove isPortfolio column and filter out any Group that has **is_portfolio = false** value.

**Details:**  Currently, the Admin Panel Groups table displays all Groups within the instance.  The **isPortfolio** column (highlighted below) displays a _Yes_ or _No_ value to distinguish the Group's level (ie, Portfolio or Program).   Since program generated data should not be editted in the Admin Panel, the isPortfolio column is not required and can be removed.  Furthermore, no Groups created within a program should be included in the Groups table.  

![image](https://user-images.githubusercontent.com/72885316/166950284-5b5452b7-ef6e-4d62-8869-a87db96979da.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
