### ISSUE TITLE
Should make Add Portfolio Groups modal wider (like Add Portfolio Projects modal)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4351]
Screenshot Example

![should_make_add_groups_portfolio_modal_wider_like_Add_projects_modal](https://user-images.githubusercontent.com/11938477/167695214-d5e0446d-8973-42dd-90cb-5ef10ddc1934.png)

**Comment by juan-rivera-2020** [comment]
Done.  
**Before:**
![image](https://user-images.githubusercontent.com/72885316/168872403-57194128-4df0-46a3-a135-53a49823aa1c.png)

**After:** 
![image](https://user-images.githubusercontent.com/72885316/168872498-61f21c70-0de5-409e-aa5e-5edcb17a60b5.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
