### ISSUE TITLE
Contract Spreadsheets:  Fix Vehicle Type dropdown component

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#4402]
**Module:**  Contract Spreadsheets
**Tab:**  Vehicles
**Component:**  Vehicle Type dropdown
**Issue:**  Dropdown option items display "No data"

![image](https://user-images.githubusercontent.com/72885316/171261549-8b215b32-d3e6-496b-9781-664d946a12d6.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
