### ISSUE TITLE
Contracts Spreadsheet - Vehicles tab - PRIME tab: null should not be a select option for "SINS or Subcategories"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4685]
Screenshot Example

![CONTRACTS_Vehicles_tab_null_should_not_be_select_option_for_SINS](https://user-images.githubusercontent.com/11938477/190436495-b6500685-5093-4f13-aa7f-89c6d220b9f2.png)

**Comment by zachegnermh** [comment]
Unable to reproduce this one 
![image](https://user-images.githubusercontent.com/109542090/190502330-7a323ae2-b73b-412b-bcab-ff2515021ae1.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed

**Comment by LAlexMHllc** [comment]
Reopening, since issue returned.
Screenshot Example

![contracts_spreadsheet_vehicles_tab_SINS_or_Subcategory_null_should_not_be_option](https://user-images.githubusercontent.com/11938477/200041067-38901038-499a-4138-aca3-efd6074001be.png)
