### ISSUE TITLE
Project Summary: When user does not have Read privilege on a tab, remove the tab and content.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#820]
EXAMPLE
When user does not have Read privilege for Notes, remove the tab and content.
Screenshot Example

![remove_notes_tab_from_facility_summary_Read_only_privilege](https://user-images.githubusercontent.com/11938477/98260674-9787bf00-1f51-11eb-8407-7c8a64bebc7b.png)

**Comment by bluenevus** [comment]
this really applies to any tab or function they don't have permissions to

**Comment by LAlexMHllc** [comment]
Reopened, since tab that user does not have Read privilege on displays again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
