### ISSUE TITLE
Create a calendar view

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mPATH#872]
This calendar view should work much like calendars in email. the user should be able to toggle between the task and issues.  It will display what ever is filtered in the filter handle with the title.  For multi day, rather than span it just put the start with the prefix start and end with the prefix end before the title else the calendar will get pretty messy.  On click, they can see details on the task in the pop up dialog that displays full information of the task or issue like the popup does in on watch.  The user should be able to toggle between day view, week view and month view and go forward or backward like email to next or previous day, week or month.  they should also be able pick a day and go to that specific day.  The user should be able to add a task or issue on the calendar.  they should also be able to delete a task or issue here.

**Comment by juan-rivera-2020** [comment]
This issue has been broken down into sub-issues (w/ "872" prefix).  Closing this issue to better manage and track by sub-issue.
