### ISSUE TITLE
Admin Feature: Roles and privileges per Program

### ISSUE THREAD

**Issue by dmpump** [MicroHealthLLC/mPATH#924]
This requirement will make it easier for assigning privileges to users as the list of users has grown significantly. 
Creating a Role tab, where you can create Roles that have selected privileges assigned to the role.
Roles are selected to be made available to selected Projects.
Then we can assign a Role to user profile.

So now, when we need to change privileges for groups, we just change it on the Role and it will push to all users that have that Role. 
![2020-11-12 11_33_35-roles and privilege - PowerPoint](https://user-images.githubusercontent.com/74024268/99083123-1785d880-2593-11eb-9110-aab57dacb1e2.png)

**Comment by LAlexMHllc** [comment]
NOTE: Project was changed to Program

**Comment by bluenevus** [comment]
I really need the ability to assign roles per program and per project.  Right now I may want to hide certain projects or give read only or give more permissions but can't.  Sometimes its across all program, sometimes its per project.  Right now its all or nothing in the system

**Comment by LAlexMHllc** [comment]
Closing, since requirement was changed to include Roles on Client Panel: default portfolio roles for ADMIN, Project, and Contract; as well as program roles for ADMIN, Project and Contract.
